#!/usr/bin/env bash
set -e

UUID=${EXTERNAL_HD_UUID:?EXTERNAL_HD_UUID is not set}
MNTPOINT=/tmp/external-hd
KEY_FILE=/run/agenix/external-hd-key
LUKSMAP=crypto_$UUID
CMD=$1

DISK=/dev/disk/by-uuid/$UUID

if [ ! -e "$DISK" ]; then
  echo "Disk $DISK not found."
  exit 1
fi

case "$CMD" in
  mount)
    mkdir -p "$MNTPOINT"
    sudo cryptsetup open --key-file "$KEY_FILE" "$DISK" "$LUKSMAP"
    sudo mount /dev/mapper/$LUKSMAP "$MNTPOINT"
    ;;
  umount)
    sudo umount "$MNTPOINT"
    sudo cryptsetup close "$LUKSMAP"
    rm -rf "$MNTPOINT"
    ;;
  *)
    echo "command '$CMD' not recognized."
    exit 1
    ;;
esac
