#!/usr/bin/env bash
# scripts/manage-vpn

VPN_CONF="/home/oliveira/.config/openvpn/vpnufop.conf"
PID_FILE="/tmp/openvpn-ufop.pid"
AUTH_FILE="/run/agenix/vpn-key"

case "$1" in
    start)
        if [ -f "$PID_FILE" ] && kill -0 $(cat "$PID_FILE") 2>/dev/null; then
            echo "OpenVPN is already running."
            exit 1
        fi

        # Point directly to the agenix secret
        openvpn --config "$VPN_CONF" --auth-user-pass "$AUTH_FILE" --daemon --writepid "$PID_FILE"

        sleep 2
        echo "nameserver 8.8.8.8" | resolvconf -a tun0
        echo "OpenVPN started."
        ;;
    stop)
        if [ ! -f "$PID_FILE" ]; then
            echo "OpenVPN is not running."
            exit 1
        fi
        kill $(cat "$PID_FILE")
        rm "$PID_FILE"
        resolvconf -d tun0
        echo "OpenVPN stopped."
        ;;
esac
