#!/usr/bin/env bash
#=============================================
PROFILE=gdrive
LOCKFILE=/tmp/lock-restic-backups-$PROFILE
BKPDIR=/home/oliveira
EXCLUDES="--exclude=$HOME/.local/share/Trash \
	--exclude=$HOME/.cache \
	--exclude=$HOME/.mozilla/firefox/oliveira/storage/default \
	--exclude=$HOME/.config/google-chrome \
	--exclude=$HOME/.local/share/torbrowser \
	--exclude=$HOME/downloads"
#TAG="--tag=NOTEBOOK"
#export PASSWORD_STORE_DIR=/home/oliveira/Sync/password-store
#export RESTIC_PASSWORD=$(pass PASSWORDS/restic)
export RESTIC_PASSWORD_FILE=/run/agenix/restic-pw
export RESTIC_REPOSITORY=rclone:ufop:restic
#=============================================
ping -c 1 8.8.8.8 > /dev/null 2>&1 
if [[ $? -ne 0 && $1 != 'help' ]];then
	echo "ABORTING: No internet connection."
	exit 2
fi
#--------------------------------------------
source /etc/profiles/per-user/oliveira/bin/restic_helper
