#!/usr/bin/env bash
# Your bemenu/rofi/wofi script

CHOICE=$(printf "VPN: Start\nVPN: Stop" | bemenu-cli)

case "$CHOICE" in
    "VPN: Start")
        sudo manage-vpn start &
        ;;
    "VPN: Stop")
        sudo manage-vpn stop &
        ;;
esac
