.TH "Grace" "1" 
.SH "NAME" 
fdf2fit \(em Script to convert Origin-4 .fdf fit parameter files to Grace 
format 
.SH "SYNOPSIS" 
.PP 
\fBfdf2fit\fR [\fIinputfile\fR]  [\fIoutputfile\fR]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBfdf2fit\fR command. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
 
.PP 
\fBfdf2fit\fR is a program that converts 
Origin-4 .fdf fit parameter files to Grace format. 
.SH "OPTIONS" 
.IP "\fBinputfile\fP         " 10 
Can be \- for standard input. 
.IP "\fBoutputfile\fP         " 10 
Can be \- for standard output. If left blank inputfile 
will be used but the suffix .fdf will be replaced by .fit . 
.SH "SEE ALSO" 
.PP 
grace(1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Torsten Werner <twerner@debian.org> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU Free Documentation 
License, Version 1.1 or any later version published by the Free 
Software Foundation; with no Invariant Sections, no Front-Cover 
Texts and no Back-Cover Texts. 
.\" created by instant / docbook-to-man, Fri 13 Jun 2008, 09:27 
